### ISSUE TITLE
BASIC認証,もしくはアクセス制限的なもの

### ISSUE THREAD

**Issue by kitaindia** [kitaindia/lagoon-mgr#13]
【相談】
どのやりかたが合っているか相談です。実際使う際とか、使う人にとってなにがベストなのかご教授ください

現状の問題
・クローズドな管理ツールなので他人から見られないようにしておきたい

改修案
１．ベーシック認証をサイト全体にかけ、パスワードをしらないと登録できないようにする（一番簡単）
２．ユーザー登録する際、メールのドメイン名を見て「登録できる・できない」をわける（会社用にメールドメインを持っている場合可能な方法）
２．１.　 ユーザー登録したときに、管理者がそのユーザーを承認するか承認しないか選べる
２．２．招待メール方式. 管理者が送ってきた招待メールからでないとユーザー登録できないようにする。

**Comment by kayhide** [comment]
こんな感じが理想です。
- ユーザーひとりひとりに管理者権限の有無をもたせる
- 管理者権限つきユーザーが新たなユーザーを登録削除できる
- 最初の管理者ユーザー自体は、エンジニアが何らかの方法（consoleから、とか）で登録してあげる

内向けのサービスなので、登録用のUIやメール招待などの機能はいらないですね。

**Comment by kayhide** [comment]
実装には、長期的なコスパ的に[devise](https://github.com/plataformatec/devise)を使うのがよいと思います。
ドキュメントの指示に従って導入したあと、いらない機能を削っていけば楽に実装できます。

**Comment by kitaindia** [comment]
なるほど、それでやってみようと思います。

devise自体も今もプロジェクトでいれてあるのでちょこっと修正すればよさそうです
