### ISSUE TITLE
デザインにBootstrapを適用する。

### ISSUE THREAD

**Issue by kayhide** [kitaindia/lagoon-mgr#3]

**Comment by kitaindia** [comment]
https://github.com/kitaindia/lagoon-mgr/pull/7

ざっとですが、適用させました。

**Comment by kayhide** [comment]
これ、デプロイされているものに反映されてます？

**Comment by kitaindia** [comment]
> これ、デプロイされているものに反映されてます？
> 反映されていると思います・・・

**Comment by kayhide** [comment]
了解ですー。
