### ISSUE TITLE
複数のアプリをまとめて登録できるようにする。

### ISSUE THREAD

**Issue by kayhide** [kitaindia/lagoon-mgr#4]

**Comment by kitaindia** [comment]
【質問】
登録方法（主にUIについて）で質問です。

今作っているものですと、一つのアプリタイトルにiOSのものとgoogle playのもので２つ用意しています。  
つまり、たとえば「LINE」ですと、google playの方にhttps://play.google.com/store/apps/details?id=jp.naver.line.android、 itunesのほうにhttps://itunes.apple.com/jp/app/line/id443904275?mt=8 を入力のような感じです。 

複数登録できるようにするとしたら、単にtextareaを一つだけ用意して、そこに登録するURLを羅列していく・・・という方法は取れないですがどのような方法がいいでしょうか。

私が考えた方法としては、
１．今あるinput fieldを複数個ひとつのページに並べて、入力できるようにする
２．csv形式でinportできるようにする

**Comment by kitaindia** [comment]
![2016-08-08 7 41 18](https://cloud.githubusercontent.com/assets/910159/17465790/92317a28-5d3b-11e6-9e7c-3c927783dcce.png)

１．
のやりかた。↑のが複数個１ページ内にならんでいるイメージ

**Comment by kayhide** [comment]
googleplay と appstore でコントローラーを分けた方がいいですね。
当然、ビューも分かれます。

routesのイメージ的には、
```ruby
resource :googleplay_apps
resource :appstore_apps
```
な感じです。

その上で、

> 単にtextareaを一つだけ用意して、そこに登録するURLを羅列していく

をするのがよいと思います。

**Comment by kayhide** [comment]
```ruby
resource :googleplay_apps do
  get :populate
  post :populate
end
```
のようにして、textareaで一行一アプリを受け付けるとよいです。

**Comment by kayhide** [comment]
よくみたら、現状でもコントローラーわかれてましたね。
質問の意図を誤解してました。
失礼しました。

**Comment by kayhide** [comment]
textareaを一つだけ用意してcsv（カンマ区切りのデータ）を入力させるのがよいのではないでしょうか。

**Comment by kitaindia** [comment]
csvで入れられるようにします！
