### ISSUE TITLE
CI する。

### ISSUE THREAD

**Issue by kayhide** [kitaindia/lagoon-mgr#8]
CI ツールを導入したほうがよいと思いますがいかがでしょう？
こんなやつ。
https://circleci.com/

導入すると例えば、
1. master に push する
2. 自動でテストが走る
3. テストが通ったら自動でデプロイされる

のようなことができます。

**Comment by kitaindia** [comment]
やってみようと思います！
1. 簡単なテストを書く
2. circle CIを導入
